.TH COREBUILD 1
.SH NAME
corebuild \- invoke ocamlbuild with a predefined set of arguments
.SH SYNOPSIS
.B corebuild
.IR ocamlbuild-option ...
.SH DESCRIPTION
.B ocamlbuild
Invokes ocamlbuild with a predefined set of arguments intended to make it easy to build against Jane Street's core library.
.SH OPTIONS
.TP
.BR ocamlbuild-option
Any option from ocamlbuild, see
.BR ocamlbuild (1)
